name: Test E2E

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: apex-website-api_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    env:
      REDIS_URL: redis://localhost:6379
      POSTGRES_DB: apex-website-api_test
      POSTGRES_USER: apex-website-api_test
      POSTGRES_PASSWORD: password

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: print message
        run: echo "Hello, World!"
      # - name: install dependencies
      #   run: yarn
      # - name: Migrate the database
      #   run: npm run migration:run
      # - name: Seed the database
      #   run: npm run db:seed
      # - name: Run E2E test
      #   run: npm run test:e2e --runInBand
